### ISSUE TITLE
How do I get back the UDP socket after getting STUN reply?

### ISSUE THREAD

**Issue by vi** [sile/rustun#2]
In the README example I know the external address of a created UDP socket from XorMappedAddress attribute. But how do I get back the socket to send custom, non-STUN datagrams elsewhere?

Do I need to somehow extract `Channel` from `Client`, then `UdpTransporter` from `Channel`, then the socket from `UdpTransporter`?

**Comment by sile** [comment]
> Do I need to somehow extract `Channel` from `Client`, then `UdpTransporter` from `Channel`, then the socket from `UdpTransporter`?

Unfortunately, `Client` does not provide a method to get a reference to the internal `Channel` and it's not so easy to implement the method. If you use `Channel` directly, you can access the innermost `UdpSocket` as the way described the above. If you does not need to handle STUN messages anymore after receiving `XorMappedAddress` metthod, this method may work well. However, in cases like that it is necessary to coexist STUN protocol and other protocol on the same UDP socket, I suppose to create a UDP transporter instance that shared by multiple transporter instances for different protocols (e.g., https://github.com/sile/rusturn/blob/master/src/client/mod.rs#L152).

**Comment by vi** [comment]
I ended up rolling my own stun and turn clients: https://crates.io/crates/stunclient https://crates.io/crates/turnclient.

**Comment by sile** [comment]
I see. I will close this issue and related ones.
