### ISSUE TITLE
Does not currently build

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [sile/rustun#3]
This wants an explicit 'dyn' in src/server.rs:164 and src/server.rs:170 (s/Box<Future/Box<dyn Future/)

That's a quick fix. However being new to rust, this one is less obvious to me - 

warning: use of deprecated item 'derive_traits_for_trackable_error_newtype': please use `#[derive(TrackableError)]` instead
  --> src/error.rs:86:1
   |
86 | derive_traits_for_trackable_error_newtype!(MessageError, MessageErrorKind);

when I mimic the syntax earlier in the code this gives me 20-odd errors.

**Comment by sile** [comment]
Thank you for letting me know about the problem!
I fixed it in #4 .

**Comment by marcbrevoort-cyberhive** [comment]
Thank you for the quick response, I confirm this builds without errors now.

**Comment by sile** [comment]
😄
